### ISSUE TITLE
[Help] build报错

### ISSUE THREAD

**Issue by UMRzcz-831** [electron-vite/electron-vite-vue#109]
#### 运行electron-builder
在windows下打包失败

node: v16.14.2
electron: v16.0.8

`To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`
  • writing effective config  file=dist\builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=robotjs@0.6.0 platform=win32 arch=x64
  • install prebuilt binary  name=robotjs version=0.6.0 platform=win32 arch=x64 napi=
  • build native dependency from sources  name=robotjs
                                          version=0.6.0
                                          platform=win32
                                          arch=x64
                                          napi=
                                          reason=prebuild-install failed with error (run with env DEBUG=electron-builder to get more information)   
                                          error=G:\project\vue-remote-desktop\node_modules\prebuild-install\node_modules\node-abi\index.js:36       
      throw new Error('Could not detect abi for version ' + target + ' and runtime ' + runtime + '.  Updating "node-abi" might help solve this issue if it is a new release of ' + runtime)
      ^

    Error: Could not detect abi for version 16.0.8 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
        at getAbi (G:\project\vue-remote-desktop\node_modules\prebuild-install\node_modules\node-abi\index.js:36:9)
        at module.exports (G:\project\vue-remote-desktop\node_modules\prebuild-install\rc.js:73:57)
        at Object.<anonymous> (G:\project\vue-remote-desktop\node_modules\prebuild-install\bin.js:9:25)
        at Module._compile (node:internal/modules/cjs/loader:1103:14)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
        at Module.load (node:internal/modules/cjs/loader:981:32)
        at Function.Module._load (node:internal/modules/cjs/loader:822:12)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
        at node:internal/main/run_main_module:17:47

  • packaging       platform=win32 arch=x64 electron=16.0.8 appOutDir=dist\win-unpacked
  ⨯ Application entry file "dist\main\index.cjs" in the "G:\project\vue-remote-desktop\dist\win-unpacked\resources\app.asar" does not exist. Seems like a wrong configuration.  failedTask=build stackTrace=Error: Application entry file "dist\main\index.cjs" in the "G:\project\vue-remote-desktop\dist\win-unpacked\resources\app.asar" does not exist. Seems like a wrong configuration.
    at error (G:\project\vue-remote-desktop\node_modules\app-builder-lib\src\asar\asarFileChecker.ts:7:12)
    at Object.checkFileInArchive (G:\project\vue-remote-desktop\node_modules\app-builder-lib\src\asar\asarFileChecker.ts:31:11)
    at WinPackager.checkFileInPackage (G:\project\vue-remote-desktop\node_modules\app-builder-lib\src\platformPackager.ts:501:7)
    at WinPackager.sanityCheckPackage (G:\project\vue-remote-desktop\node_modules\app-builder-lib\src\platformPackager.ts:549:5)
    at WinPackager.doPack (G:\project\vue-remote-desktop\node_modules\app-builder-lib\src\platformPackager.ts:310:5)
    at WinPackager.pack (G:\project\vue-remote-desktop\node_modules\app-builder-lib\src\platformPackager.ts:136:5)
    at Packager.doBuild (G:\project\vue-remote-desktop\node_modules\app-builder-lib\src\packager.ts:441:9)
    at Object.executeFinally (G:\project\vue-remote-desktop\node_modules\builder-util\src\promise.ts:12:14)
    at Packager._build (G:\project\vue-remote-desktop\node_modules\app-builder-lib\src\packager.ts:376:31)
    at Packager.build (G:\project\vue-remote-desktop\node_modules\app-builder-lib\src\packager.ts:337:12)
    at Object.executeFinally (G:\project\vue-remote-desktop\node_modules\builder-util\src\promise.ts:12:14)`
A clear and concise description of what you are confusing about.

#### package.json

[项目package.json](https://github.com/UMRzcz-831/vue-remote-desktop/blob/main/package.json)

**Comment by caoxiemeihao** [comment]
报错很明显啊，你的 native 包 electron-builder 打包不了啊  

不在乎应用体积大小的话，native 包不需要再次构建也能用，去看 sqlite3 的打包案例
