### ISSUE TITLE
[Help] 打包失败

### ISSUE THREAD

**Issue by yyman001** [electron-vite/electron-vite-vue#134]
#### Describe the problem you Confuse
打包下载某个依赖无法下载, 挂着全局vnp也没效果, 更换 包源也不行.
https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-3.0.4.1/nsis-3.0.4.1.7z

### 环境
- win10
- node 16.14.2

#### More detail (optional)
```cmd
C:\my_git_project\electron-vite-vue-main>npm run build
Debugger attached.

> electron-vue-vite@1.0.0 prebuild
> vue-tsc --noEmit --p packages/renderer/tsconfig.json && node scripts/build.mjs

Debugger attached.
Waiting for the debugger to disconnect...
Debugger attached.
vite v2.9.9 building for production...
✓ 1 modules transformed.
../../dist/main/index.cjs   1.18 KiB / gzip: 0.71 KiB
../../dist/main/index.cjs.map 3.15 KiB
vite v2.9.9 building for production...
✓ 3 modules transformed.
../../dist/preload/index.cjs   1.48 KiB / gzip: 0.70 KiB
../../dist/preload/index.cjs.map 3.62 KiB
(node:7120) [DEP0025] DeprecationWarning: sys is deprecated. Use util instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
vite v2.9.9 building for production...
✓ 17 modules transformed.
../../dist/renderer/vite.43a7a287.svg       1.49 KiB
../../dist/renderer/electron.fe1dfbad.png   61.65 KiB
../../dist/renderer/vue.03d6d6da.png        6.69 KiB
../../dist/renderer/index.html              0.50 KiB
../../dist/renderer/index.930ebbad.css      0.59 KiB / gzip: 0.33 KiB
../../dist/renderer/index.597874e7.js       52.41 KiB / gzip: 21.16 KiB
../../dist/renderer/index.597874e7.js.map   534.37 KiB
Waiting for the debugger to disconnect...

> electron-vue-vite@1.0.0 build
> electron-builder

Debugger attached.
  • electron-builder  version=23.0.3 os=10.0.19043
  • loaded configuration  file=C:\my_git_project\electron-vite-vue-main\electron-builder.json5
  • description is missed in the package.json  appPackageFile=C:\my_git_project\electron-vite-vue-main\package.json
  • writing effective config  file=release\1.0.0\builder-effective-config.yaml
  • packaging       platform=win32 arch=x64 electron=18.2.0 appOutDir=release\1.0.0\win-unpacked
  • default Electron icon is used  reason=application icon is not set
  • building        target=nsis file=release\1.0.0\electron-vue-vite_1.0.0.exe archs=x64 oneClick=false perMachine=false
  ⨯ Get "https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-3.0.4.1/nsis-3.0.4.1.7z": dial tcp 127.0.0.1:443: connectex: No connection could be made because the target machine actively refused it.
github.com/develar/app-builder/pkg/download.(*Downloader).follow.func1
        /Volumes/data/Documents/app-builder/pkg/download/downloader.go:206
github.com/develar/app-builder/pkg/download.(*Downloader).follow
        /Volumes/data/Documents/app-builder/pkg/download/downloader.go:234
github.com/develar/app-builder/pkg/download.(*Downloader).DownloadNoRetry
        /Volumes/data/Documents/app-builder/pkg/download/downloader.go:128
github.com/develar/app-builder/pkg/download.(*Downloader).Download
        /Volumes/data/Documents/app-builder/pkg/download/downloader.go:112
github.com/develar/app-builder/pkg/download.DownloadArtifact
        /Volumes/data/Documents/app-builder/pkg/download/artifactDownloader.go:107
github.com/develar/app-builder/pkg/download.ConfigureArtifactCommand.func1
        /Volumes/data/Documents/app-builder/pkg/download/artifactDownloader.go:27
github.com/alecthomas/kingpin.(*actionMixin).applyActions
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28
github.com/alecthomas/kingpin.(*Application).applyActions
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557
github.com/alecthomas/kingpin.(*Application).execute
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390
github.com/alecthomas/kingpin.(*Application).Parse
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222
main.main
        /Volumes/data/Documents/app-builder/main.go:90
runtime.main
        /usr/local/Cellar/go/1.17/libexec/src/runtime/proc.go:255
runtime.goexit
        /usr/local/Cellar/go/1.17/libexec/src/runtime/asm_amd64.s:1581  
  ⨯ C:\my_git_project\electron-vite-vue-main\node_modules\.pnpm\registry.npmmirror.com+app-builder-bin@4.0.0\node_modules\app-builder-bin\win\x64\app-builder.exe process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1  failedTask=build stackTrace=Error: C:\my_git_project\electron-vite-vue-main\node_modules\.pnpm\registry.npmmirror.com+app-builder-bin@4.0.0\node_modules\app-builder-bin\win\x64\app-builder.exe process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1
    at ChildProcess.<anonymous> (C:\my_git_project\electron-vite-vue-main\node_modules\.pnpm\registry.npmmirror.com+builder-util@23.0.2\node_modules\builder-util\src\util.ts:250:14)
    at Object.onceWrapper (node:events:646:26)
    at ChildProcess.emit (node:events:526:28)
    at ChildProcess.cp.emit (C:\my_git_project\electron-vite-vue-main\node_modules\.pnpm\registry.npmmirror.com+cross-spawn@7.0.3\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
From previous event:
    at processImmediate (node:internal/timers:466:21)
From previous event:
    at NsisTarget.buildInstaller (C:\my_git_project\electron-vite-vue-main\node_modules\.pnpm\registry.npmmirror.com+app-builder-lib@23.0.3\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:228:29)
    at NsisTarget.finishBuild (C:\my_git_project\electron-vite-vue-main\node_modules\.pnpm\registry.npmmirror.com+app-builder-lib@23.0.3\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:131:9)
    at async Promise.all (index 1)
    at AsyncTaskManager.awaitTasks (C:\my_git_project\electron-vite-vue-main\node_modules\.pnpm\registry.npmmirror.com+builder-util@23.0.2\node_modules\builder-util\src\asyncTaskManager.ts:65:25)
    at Packager.doBuild (C:\my_git_project\electron-vite-vue-main\node_modules\.pnpm\registry.npmmirror.com+app-builder-lib@23.0.3\node_modules\app-builder-lib\src\packager.ts:453:5)
    at Object.executeFinally (C:\my_git_project\electron-vite-vue-main\node_modules\.pnpm\registry.npmmirror.com+builder-util@23.0.2\node_modules\builder-util\src\promise.ts:12:14)
    at Packager._build (C:\my_git_project\electron-vite-vue-main\node_modules\.pnpm\registry.npmmirror.com+app-builder-lib@23.0.3\node_modules\app-builder-lib\src\packager.ts:376:31)
    at Packager.build (C:\my_git_project\electron-vite-vue-main\node_modules\.pnpm\registry.npmmirror.com+app-builder-lib@23.0.3\node_modules\app-builder-lib\src\packager.ts:337:12)
    at Object.executeFinally (C:\my_git_project\electron-vite-vue-main\node_modules\.pnpm\registry.npmmirror.com+builder-util@23.0.2\node_modules\builder-util\src\promise.ts:12:14)
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
```

**Comment by yyman001** [comment]
配置
.yarnrc
```cmd
registry "https://registry.npm.taobao.org/"
electron_mirror "https://npm.taobao.org/mirrors/electron/"
electron_builder_binaries_mirror "http://npm.taobao.org/mirrors/electron-builder-binaries/"
```
yarn run build
完美解决
