### ISSUE TITLE
[Help] TypeError: electron is not a function

### ISSUE THREAD

**Issue by RibsStorm** [electron-vite/electron-vite-vue#197]
#### Describe the problem you confuse
运行 npm run dev,就报这个错误.

failed to load config from /Users/xxxx/XXX/XXXScanner/vite.config.js
error when starting dev server:
TypeError: electron is not a function
    at file:///Users/xxx/XXX/XXXScanner/vite.config.js.mjs?t=1658372688736:82:5
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadConfigFromBundledFile (file:///Users/xxxx/XXX/XXXScanner/node_modules/vite/dist/node/chunks/dep-1513d487.js:62803:21)
    at async loadConfigFromFile (file:///Users/xxxx/XXX/XXXScanner/node_modules/vite/dist/node/chunks/dep-1513d487.js:62692:28)
    at async resolveConfig (file:///Users/xxxx/XXX/XXXScanner/node_modules/vite/dist/node/chunks/dep-1513d487.js:62344:28)
    at async createServer (file:///Users/xxxx/XXX/XXXScanner/node_modules/vite/dist/node/chunks/dep-1513d487.js:58962:20)
    at async CAC.<anonymous> (file:///Users/xxxx/XXX/XXXScanner/node_modules/vite/dist/node/cli.js:699:24)

============================================================================================
环境是这样的:
node: 16.16.0
electron: 19.0.8

求大佬帮忙看看~

**Comment by caoxiemeihao** [comment]
我这好好的

**Comment by RibsStorm** [comment]
我直接把项目掐了,全部删掉,重启电脑,重新搞.
然后又好了.麻了~

**Comment by SOUTHYYY** [comment]
Try to remove `"type": "module"` from your package,.json file
https://www.npmjs.com/package/vite-plugin-electron

> Currently, "type": "module" is not supported in Electron

> #### Describe the problem you confuse
> 运行 npm run dev,就报这个错误.
> 
> failed to load config from /Users/xxxx/XXX/XXXScanner/vite.config.js error when starting dev server: TypeError: electron is not a function at file:///Users/xxx/XXX/XXXScanner/vite.config.js.mjs?t=1658372688736:82:5 at ModuleJob.run (node:internal/modules/esm/module_job:198:25) at async Promise.all (index 0) at async ESMLoader.import (node:internal/modules/esm/loader:385:24) at async loadConfigFromBundledFile (file:///Users/xxxx/XXX/XXXScanner/node_modules/vite/dist/node/chunks/dep-1513d487.js:62803:21) at async loadConfigFromFile (file:///Users/xxxx/XXX/XXXScanner/node_modules/vite/dist/node/chunks/dep-1513d487.js:62692:28) at async resolveConfig (file:///Users/xxxx/XXX/XXXScanner/node_modules/vite/dist/node/chunks/dep-1513d487.js:62344:28) at async createServer (file:///Users/xxxx/XXX/XXXScanner/node_modules/vite/dist/node/chunks/dep-1513d487.js:58962:20) at async CAC. (file:///Users/xxxx/XXX/XXXScanner/node_modules/vite/dist/node/cli.js:699:24)
> 
> ============================================================================================ 环境是这样的: node: 16.16.0 electron: 19.0.8
> 
> 求大佬帮忙看看~
