### ISSUE TITLE
[Bug] npm run dev后报错

### ISSUE THREAD

**Issue by yutf** [electron-vite/electron-vite-vue#238]
安装依赖后启动报以下错误：
failed to load config from E:\git\shield-digit3\electron-vite-vue\vite.config.ts
error when starting dev server:
Error: Cannot find module 'node:path'
Require stack:
- E:\git\shield-digit3\electron-vite-vue\node_modules\vite\dist\node-cjs\publicUtils.cjs
- E:\git\shield-digit3\electron-vite-vue\node_modules\vite\index.cjs
- E:\git\shield-digit3\electron-vite-vue\vite.config.ts
- E:\git\shield-digit3\electron-vite-vue\node_modules\vite\dist\node\chunks\dep-5cb728cb.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (E:\git\shield-digit3\electron-vite-vue\node_modules\vite\dist\node-cjs\publicUtils.cjs:5:14)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Object._require.extensions.<computed> [as .js] (file:///E:/git/shield-digit3/electron-vite-vue/node_modules/vite/dist/node/chunks/dep-5cb728cb.js:63008:17)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-vue-vite@2.0.0 dev: `vite`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-vue-vite@2.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above..

**Comment by caoxiemeihao** [comment]
拉下来就报错？

**Comment by yutf** [comment]
![image](https://user-images.githubusercontent.com/9894922/184066060-f3bcb0f1-9f3a-47e6-948a-a72efd3a634a.png)
是的，没有修改任何代码，是否跟nodejs版本有关系？我目前是V14.17.0

**Comment by yi-Xu-0100** [comment]
@yutf 看起来像是 npm i 没安装完？

**Comment by yutf** [comment]
升级nodejs后正常了，建议更新package.json中关于node版本的描述或者修复这个问题

**Comment by caoxiemeihao** [comment]
https://github.com/vitejs/vite/blob/5a182840b6d2630844038d91747dfeb5161dc777/packages/vite/package.json#L34-L36

```json
  "engines": {
    "node": "^14.18.0 || >=16.0.0"
  },
```

确实该升级了
