### ISSUE TITLE
[Help] Mac 下打包报错 Seems like a wrong configuration

### ISSUE THREAD

**Issue by DusuWen** [electron-vite/electron-vite-vue#259]
```shell
/Users/drlouie/.nvm/versions/node/v16.15.0/bin/npm run build

> electron-vue-vite@2.0.0 build
> vite build && electron-builder

vite v3.1.0 building for production...
✓ 1457 modules transformed.
dist/index.html           0.58 KiB
dist/style.cdaa60d3.css   314.04 KiB / gzip: 42.66 KiB
dist/index.cb0f4b25.js    879.34 KiB / gzip: 284.54 KiB

(!) Some chunks are larger than 500 KiB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/guide/en/#outputmanualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
vite v3.1.0 building for production...
✓ 1 modules transformed.
dist/electron/preload/index.js   1.54 KiB / gzip: 0.74 KiB
dist/electron/preload/index.js.map 3.87 KiB
vite v3.1.0 building for production...
✓ 1 modules transformed.
dist/electron/main/index.js   1.69 KiB / gzip: 0.91 KiB
dist/electron/main/index.js.map 5.03 KiB
  • electron-builder  version=23.3.3 os=21.5.0
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=darwin arch=x64 electron=20.1.3 appOutDir=dist/mac
  • default Electron icon is used  reason=application icon is not set
  ⨯ Application entry file "dist/electron/main/index.js" in the "/Users/drlouie/WebstormProjects/electron-vite-vue/dist/mac/electron-vue-vite.app/Contents/Resources/app.asar" does not exist. Seems like a wrong configuration.  failedTask=build stackTrace=Error: Application entry file "dist/electron/main/index.js" in the "/Users/drlouie/WebstormProjects/electron-vite-vue/dist/mac/electron-vue-vite.app/Contents/Resources/app.asar" does not exist. Seems like a wrong configuration.
    at error (/Users/drlouie/WebstormProjects/electron-vite-vue/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:7:12)
    at Object.checkFileInArchive (/Users/drlouie/WebstormProjects/electron-vite-vue/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:31:11)
    at MacPackager.checkFileInPackage (/Users/drlouie/WebstormProjects/electron-vite-vue/node_modules/app-builder-lib/src/platformPackager.ts:503:7)
    at MacPackager.sanityCheckPackage (/Users/drlouie/WebstormProjects/electron-vite-vue/node_modules/app-builder-lib/src/platformPackager.ts:551:5)
    at MacPackager.doPack (/Users/drlouie/WebstormProjects/electron-vite-vue/node_modules/app-builder-lib/src/platformPackager.ts:312:5)
    at MacPackager.pack (/Users/drlouie/WebstormProjects/electron-vite-vue/node_modules/app-builder-lib/src/macPackager.ts:192:7)
    at Packager.doBuild (/Users/drlouie/WebstormProjects/electron-vite-vue/node_modules/app-builder-lib/src/packager.ts:441:9)
    at Object.executeFinally (/Users/drlouie/WebstormProjects/electron-vite-vue/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/Users/drlouie/WebstormProjects/electron-vite-vue/node_modules/app-builder-lib/src/packager.ts:376:31)
    at Packager.build (/Users/drlouie/WebstormProjects/electron-vite-vue/node_modules/app-builder-lib/src/packager.ts:337:12)
    at Object.executeFinally (/Users/drlouie/WebstormProjects/electron-vite-vue/node_modules/builder-util/src/promise.ts:12:14)

Process finished with exit code 1
```

**Comment by caoxiemeihao** [comment]
提供下复现 Demo

**Comment by DusuWen** [comment]
> 提供下复现 Demo

你好，[demo](https://github.com/DusuWen/electron-vite-vue)如下

**Comment by DusuWen** [comment]
> 

你好，我npm create electron-vite之后，使用`ELECTRON_MIRROR="https://npmmirror.com/mirrors/electron/" npm i`安装，以及在package.json中添加
```
  "build": {
    "electronDownload": {
      "mirror": "https://npm.taobao.org/mirrors/electron/"
    }
  },
```
后build报错Seems like a wrong configuration

**Comment by DusuWen** [comment]
> 提供下复现 Demo

你好，我npm create electron-vite之后，使用`ELECTRON_MIRROR="https://npmmirror.com/mirrors/electron/" npm i`安装，以及在package.json中添加
```
  "build": {
    "electronDownload": {
      "mirror": "https://npm.taobao.org/mirrors/electron/"
    }
  },
```
后build报错Seems like a wrong configuration

**Comment by DusuWen** [comment]
在package.json中添加
```
  "build": {
    "files": [
      "dist"
    ]
  }
```
即可
