### ISSUE TITLE
[Bug] the title of bug report

### ISSUE THREAD

**Issue by xieerduos** [electron-vite/electron-vite-vue#265]
```bash
npm install

npm run dev
```

运行上面命令直接报错？ 最基本的代码都跑不通，这么拉跨吗？

```bash
D:\desktop\electron-vite-boilerplate\packages\renderer\vite.config.ts:40
      config.base ??= "./";
                  ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object._require.extensions.<computed> [as .js] (file:///D:/desktop/electron-vite-boilerplate/node_modules/vite/dist/node/chunks/dep-6b3a5aff.js:63514:24)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at loadConfigFromBundledFile (file:///D:/desktop/electron-vite-boilerplate/node_modules/vite/dist/node/chunks/dep-6b3a5aff.js:63522:21)
    at loadConfigFromFile (file:///D:/desktop/electron-vite-boilerplate/node_modules/vite/dist/node/chunks/dep-6b3a5aff.js:63381:34)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1        
npm ERR! electron-vite-boilerplate@2.0.0 dev: `node scripts/watch.mjs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-vite-boilerplate@2.0.0 dev script.    
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.```bash

```

**Comment by caoxiemeihao** [comment]
提个 issues 都不知道往哪儿提？你确定你 node 版本是对的？

**Comment by xieerduos** [comment]
> 提个 issues 都不知道往哪儿提？你确定你 node 版本是对的？

版本确实不对

electron-vite-boilerplate node 按照package.json里面的要求，但是没有跑起来

**Comment by caoxiemeihao** [comment]
用了镜像？我本地用的 yarn，没改任何东西装上依赖就能跑。
