### ISSUE TITLE
[Help] As soon as I add fs or fs-extra, Graceful-fs errors

### ISSUE THREAD

**Issue by kevjustice** [electron-vite/electron-vite-vue#355]
I have setup a fresh project using electron-vite.  As soon as I install either fs or fs-extra and try to use it, the following error shows up:

graceful-fs.js:25 Uncaught TypeError: Cannot define property Symbol(graceful-fs.queue), object is not extensible
    at Function.defineProperty (<anonymous>)
    at publishQueue (graceful-fs.js:25:10)
    at node_modules/graceful-fs/graceful-fs.js (graceful-fs.js:46:3)
    at __require (chunk-RSJERJUL.js?v=60342089:3:50)
    at node_modules/fs-extra/lib/fs/index.js (index.js:5:12)
    at __require (chunk-RSJERJUL.js?v=60342089:3:50)
    at node_modules/fs-extra/lib/index.js (index.js:5:6)
    at __require (chunk-RSJERJUL.js?v=60342089:3:50)
    at index.js:16:1

I'm sure I'm just not understanding something as I can tell that graceful-fs is included in the build package.  I did try including graceful-fs-extra but got the same error.

I need to use fs.readJsonSync (or something similar) so any help is appreciated!!!

**Comment by caoxiemeihao** [comment]
Can you provide a minimal reproduction repo?

**Comment by caoxiemeihao** [comment]
See here 👉 https://github.com/caoxiemeihao/nuxt-electron/issues/16#issuecomment-1487849598
