### ISSUE TITLE
Unexpected token '??=' on fresh clone and npm install

### ISSUE THREAD

**Issue by kristianh00** [electron-vite/electron-vite-vue#374]
When freshly cloning the package and running npm install, building the project using npm run build, or simply npx vue-tsc will result with following error:

```
electron-vue-vite@2.0.0 build /home/korisnik/dev/test/electron-vite-vue
vue-tsc --noEmit && vite build && electron-builder

/home/korisnik/dev/test/electron-vite-vue/node_modules/@volar/vue-language-core/out/generators/template.js:553
                localVars[varName] ??= 0;
                                   ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/korisnik/dev/test/electron-vite-vue/node_modules/@volar/vue-language-core/out/index.js:18:14)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-vue-vite@2.0.0 build: `vue-tsc --noEmit && vite build && electron-builder`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-vue-vite@2.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/korisnik/.npm/_logs/2023-04-21T14_26_20_144Z-debug.log
```

I am using node version 14, but using 16 also does not work.
Help would be appreciated.

Kind regards.

**Comment by caoxiemeihao** [comment]
Can you provide a minimal reproduction Deom?

**Comment by huangtian615** [comment]
same error

**Comment by huangtian615** [comment]
> Can you provide a minimal reproduction Deom?

I used Mac to initialize the project and there was no problem with packaging, but when I planned to switch to Windows and package the Windows version, I reported this error

**Comment by yikus-tjq** [comment]
应该是node版本问题导致的，localVars[varName] ??= 0 就相当于 localVars[varName] = localVars[varName] ?? (0), 而??是es新的语法，你升级下node试试

**Comment by timalanfarrow** [comment]
@huangtian615 I had this error using Node v14.19.1. I upgrade to v16.17.0 and ran the command just fine.

**Comment by kristianh00** [comment]
Upgrading to node version 18 fixed the issue. Issue was that my terminal kept forgetting node version change.

**Comment by so1ve** [comment]
Actually this is a vue-tsc error.
